### ISSUE TITLE
Why using both ALE and COC

### ISSUE THREAD

**Issue by sandangel** [oblitum/dotfiles#4]
Hi thanks for sharing your dotfiles, it's awesome.
One thing I don't understand is why you have to use both COC, and ALE's diagnostics?
Is that COC already provided diagnostics info out of the box?

**Comment by oblitum** [comment]
Hi. Currently I use ALE as linting fallback (though it started to provide LSP support, which I don't use) for stuff coc.nvim doesn't yet support:

https://github.com/oblitum/dotfiles/blob/2332ad773b324389eb8e401d957e080a77161b32/.vimrc#L1178-L1187

ALE isn't focused on LSP, which makes it a more general tool for whatever filetype I didn't manage to configure coc.nvim with.

**Comment by oblitum** [comment]
Other people's reasons I've see are:

- Use coc.nvim's [`displayByAle`](https://github.com/neoclide/coc.nvim/blob/cb795977ba16af0a9a981196ba22c70676353afb/data/schema.json#L377-L381) to use coc.nvim as additional diagnostics source for ALE, instead of having coc at the forefront for that (I don't like this because of diagnostics duplication between sources).
- Use coc.nvim just for completion, while ALE for linting, because it works for more stuff than LSP, with diverse linting tools.
